=== JeresB/XML-CIR3/etudiant1.dtd
<!ELEMENT etudiants (etudiant*)>
<!ELEMENT etudiant (nom, prenom, adr_mail, tel*, age?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT adr_mail (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ATTLIST etudiant
  login ID #REQUIRED
  password CDATA #IMPLIED>

=== JeresB/XML-CIR3/etudiant1.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- <!DOCTYPE etudiants SYSTEM "etudiant1.dtd"> -->
<etudiants
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="etudiant1.xsd">
	<etudiant login="Jeres" password="motdepasse">
		<nom>Boiselet</nom>
		<prenom>Jeres</prenom>
		<adr_mail>boiselet.jeremy@gmail.com</adr_mail>
		<tel>07 80 31 63 48</tel>
		<age>20</age>
	</etudiant>
	<etudiant login="Tete">
		<nom>Dupont</nom>
		<prenom>Théo</prenom>
		<adr_mail>dupont.tete@gmail.com</adr_mail>
		<tel>06 02 45 48 95</tel>
		<age>20</age>
	</etudiant>
	<etudiant login="JF" password="easy">
		<nom>Tetchi</nom>
		<prenom>Jean-François</prenom>
		<adr_mail>tetchi.jf@gmail.com</adr_mail>
		<tel>06 02 12 95 74</tel>
		<tel>06 52 48 56 32</tel>
	</etudiant>
	<etudiant login="Tristan">
		<nom>Le Lièvre-Ropers</nom>
		<prenom>Tristan</prenom>
		<adr_mail>tristan.lelivre@gmail.com</adr_mail>
		<tel>06 02 65 98 84</tel>
	</etudiant>
	<etudiant login="Lancelot" password="jelanceleau">
		<nom>Le Meur</nom>
		<prenom>Lancelot</prenom>
		<adr_mail>lancelot.le-meur@gmail.com</adr_mail>
		<age>20</age>
	</etudiant>
</etudiants>
